language: node_js
node_js:
- '4.0'
- '8.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: Zv75/kLyHDxaSC/hV99TOS0xkKH8I4EUYGC5Dx6RnmbazDWReIZmNjyzA8a9YAvvmFpxDT7AbzWThYYCBxY5UyPabn49bgQ94NvRcvejyaHn13jwrEGCT2eZxIMtj5Fi73l2ZV4hKOxVLuGUYc2ubO9WG3VlOjam/GHwilve0Ps=
  file:
    - "datamap-interface.js"
    - "datamap-interface.min.js"
  on:
    tags: true
    node: '8.0'
